Program Math;
Uses crt;
Begin
     clrscr;
     Writeln('3 + 3 = ', 3 + 3);
     Writeln('7 - 3 = ', 7 - 3);
     Writeln('2 x 3 = ', 2 * 3);
     Writeln('(2 + 3) * 2 = ', (2+3)*2);
     Writeln('2 + 3 * 2 = ', 2+3*2);
     Writeln('5 mod 3 = ', 5 mod 3);
     Writeln('10 div 3 = ', 10 div 3);
     Writeln('10 / 3 = ', 10/3:0:2);
     Writeln('10 / 3 = ', 10/3);

     Writeln;
     Writeln('----- Press <Enter> To Exit -----');
     Readln;
End.